version: '3'

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"

  mongodb:
    image: mongo:latest
    expose:
      - "27017"

  web:
    build: .
    command: node dist/main.js
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb

  nodejs_worker:
    build: .
    command: node dist/crawler.main.js
    depends_on:
      - redis
      - mongodb

  python_worker:
    build: ./workers
    depends_on:
      - redis
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - web